name: Run Backend Tests

on:
  push:

jobs:
          
  Unit_Tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant permissions
        run: chmod +x mandrake-backend/./gradlew
            
      - name: Run Unit Tests
        run: mandrake-backend/./gradlew -p mandrake-backend runUnitTests
